- import_playbook: build.yml

- hosts: local
  vars:
    build_dir: '{{ project_root }}/dist'
  tasks:
    - name: actual pip
      shell: which pip
      register: result
      when: pip is undefined

    - set_fact:
        pip: '{{ result.stdout_lines[0] }}'
      when: pip is undefined

    - name: find whl file
      find:
        paths: '{{ build_dir }}'
        file_type: file
        patterns: '*.whl'
      register: found

    - set_fact:
        wheel: '{{ found.files[0].path }}'

    - debug:
        msg: '{{ wheel }}'

    - name: uninstall previous version
      pip:
        name: '{{ project_name }}'
        state: absent
        executable: '{{ pip }}'
      ignore_errors: yes

    - name: install whl file
      pip:
        name: '{{ wheel }}'
        executable: '{{ pip }}'
